# https://docs.gradle.org/current/userguide/toolchains.html
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
# Assume /jdks with specific JDK versions exists on all developers local working environment. Can be symbolic links too.
# Download the JDKs from https://adoptium.net/en-GB/temurin/releases
org.gradle.java.installations.paths=/Users/jdks/jdk-23.0.2,/Users/jdks/jdk-25.0.2